name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create-dir
      run: mkdir build
    - name: go-to-dirrectory
      run: cd build
    - name: configure
      run: ls ../
    - name: make -j$(nproc)
      run: make -j$(nproc)
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
